[package]
name = "myrust"
version = "0.1.0"
edition = "2025"
authors = ["Frederic Horanin <fhornain@gmail.com>"]

[dependencies]
actix-web.workspace = true
env_logger.workspace = true
log.workspace = true
